

name: VIS

on: # укажите сборку для запуска автоматического ci/cd
    push:
        branches:
            - "master"
            
jobs: 
    build:
        name: Build Docker image
        runs-on: ubuntu-latest # укажите ОС для работы приложения
        steps:
            - # Клонируйте код приложения в ОС
                name: Checkout
                uses: actions/checkout@v3
            - # Войдите в docker hub используя токен
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - # создайте экземпляр build kit builder
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            - #  создайте образ контейнера и отправьте его в DockerHub с помощью тегаclockbox
               name: Build and push
               uses: docker/build-push-action@v4
               with:
                 context: .
                 file: ./Dockerfile
                 push: true
                 tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
               



            
